language: go
go:
  - '1.11.x'
  - '1.12.x'

env:
  global:
    - LD_LIBRARY_PATH="/usr/local/lib":${LD_LIBRARY_PATH}
    - GO111MODULE=on

addons:
  apt:
    packages:
      - libonig-dev

script:
  - go test -v --cover -race
