dist: trusty
language: go
go:
  - '1.11.x'
  - '1.12.x'

env:
  global:
    - LD_LIBRARY_PATH="/usr/local/lib":${LD_LIBRARY_PATH}
    - GO111MODULE=on
addons:
  apt:
    packages:
      - libonig-dev

before_install:
  - sudo apt-get install -y dpkg  # dpkg >= 1.17.5ubuntu5.8, which fixes https://bugs.launchpad.net/ubuntu/+source/dpkg/+bug/1730627- sudo dpkg -i libonig-dev_6.9.1-1_amd64.deb
  - wget http://archive.ubuntu.com/ubuntu/pool/universe/libo/libonig/libonig5_6.9.1-1_amd64.deb
  - sudo dpkg -i libonig5_6.9.1-1_amd64.deb
  - wget http://archive.ubuntu.com/ubuntu/pool/universe/libo/libonig/libonig-dev_6.9.1-1_amd64.deb
  - sudo dpkg -i libonig-dev_6.9.1-1_amd64.deb
script:
  - go test -v --cover -race
